[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
target-version = "py312"
# Lint rule sets: pyflakes/pycodestyle errors, isort, bugbear, comprehensions, etc.
select = ["E", "F", "W", "I", "B", "C4"]
ignore = []
# Directories to include/exclude as needed
exclude = ["build", "dist", ".venv"]

[tool.ruff.format]
# Keep black as the formatter; ruff won't format if you don’t call `ruff format`.
quote-style = "preserve"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-q"
testpaths = ["tests"]
